CREATE TABLE IF NOT EXISTS cocktails (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    image_url TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS materials (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cocktail_materials (
    cocktail_id INTEGER NOT NULL,
    material_id INTEGER NOT NULL,
    quantity INTEGER,
    unit VARCHAR(128)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cocktail_material_images (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    data LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shops (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_cocktails (
    shop_id INTEGER NOT NULL,
    cocktail_id INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_tables (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    shop_id INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_orders (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    table_id INTEGER NOT NULL,
    shop_cocktail_id INTEGER NOT NULL,
    is_provided bool DEFAULT false
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
